export const strings = {
  error_corrige_campo: 'Corrige aquí',
  error_campo_empty: 'Completa aquí',
  continuar: 'Continuar',
  usar_otra_cuenta: 'Usar otra cuenta',
  new_owner: 'Nuevo propietario',
  complete_data: 'Completa los datos',
  update_owner: 'Editando propietario',
  name: 'Nombre',
  address: 'Dirección',
  email: 'Email',
  phone: 'Teléfono',
  region: 'Región',
  notes: 'Notas',
  regional_id: 'DNI / DU / Pasaporte / Identificación regional',
  fiscal_type: 'Tipo fiscal',
  web_page: 'Página web',  
<<<<<<< Updated upstream
  product_name:'Nombre Producto',
  category:'Categoria',
  unit:'Unidad de Medida',
  barCode:'Código de barras', 
  qr_code:'Código QR',
  currentQuantity:"Cantidad Actual",
  minQuantity:'Cantidad Mínima',
  cost:'Costo',
  tax:'Impuesto',
  margin:'Margen',
  finalPrice:'Precio',
  date:'Fecha',
  hour:'Hora',
  temp:'Temperatura Corporal',
  weight:'Peso',
  anamnesis:'Historia Clínica',
  amount:'Ingresa Cantidad',
  payment_method:'Método de Pago',
  movement_type:'Tipo de Movimiento',
  update_cash:'Editando Movimiento de Caja',
=======
  subscription_until: 'Suscripción hasta',
  race: 'Raza',
  pelage : 'Pelaje',
  gender: 'Género',
  character: 'Carácter',
  birthday: 'Nacimiento',
  weight: 'Peso',
  chip: 'Chip',
  update_category: 'Editando categoría',
  new_category: 'Nueva categoría',
>>>>>>> Stashed changes
};