export const strings = {
  error_corrige_campo: 'Corrige aquí',
  error_campo_empty: 'Completa aquí',
  continuar: 'Continuar',
  usar_otra_cuenta: 'Usar otra cuenta',
  new_owner: 'Nuevo propietario',
  complete_data: 'Completa los datos',
  update_owner: 'Editando propietario',
  name: 'Nombre',
  address: 'Dirección',
  email: 'Email',
  phone: 'Teléfono',
  region: 'Región',
  notes: 'Notas',
  regional_id: 'DNI / DU / Pasaporte / Identificación regional',
  fiscal_type: 'Tipo fiscal',
  web_page: 'Página web',  
  subscription_until: 'Suscripción hasta',
  race: 'Raza',
  pelage : 'Pelage',
  gender: 'Género',
  character: 'Carácter',
  birthday: 'Nacimiento',
  weight: 'Peso',
  chip: 'Chip',
  
};